import "./globals.css";
import Head from "next/head"; // Import Head component from Next.js
import { AuthProvider } from "./Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Add the link to Anakotmai font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Anakotmai:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <style>
          {`
            body {
              font-family: 'Anakotmai, sans-serif';
            }
          `}
        </style>
      </Head>
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
